export const PAGE_STYLESHEETS = {
  "/": [
    "/assets/css/ZTO/Home/all.min.css",
    "/assets/css/ZTO/Home/bootstrap.min.css",
    "/assets/css/ZTO/Home/slick.css",
    "/assets/css/ZTO/Home/slick-theme.css",
    "/assets/css/ZTO/header.css",
    "/assets/css/ZTO/footer.css",
    "/assets/css/ZTO/Home/stylehome.css",
    "/assets/css/ZTO/Home/custom.css",
    "/assets/css/ZTO/Home/select2.min.css",
    "/assets/css/ZTO/Home/responsive.css",
    "/assets/css/ZTO/inline_style.css",
  ],
  "/activity/result": [
    "/assets/css/ZTO/bootstrap.css",
    "/assets/css/ZTO/style.css",
    "/assets/css/ZTO/Home/all.min.css",
    "/assets/css/ZTO/style-home.css",
    "/assets/css/ZTO/Home/slicknav.min.css",
    "/assets/css/ZTO/Home/select2.min.css",
    "/assets/css/ZTO/custom.css",
    "/assets/css/ZTO/responsive.css",
    "/assets/css/ZTO/header.css",
    "/assets/css/ZTO/footer.css",
    "/assets/css/ZTO/theme.css",
    "/assets/css/ZTO/inline_style.css",
    "/assets/css/ZTO/Romanian.css",
    "/assets/css/ZTO/components/activityresult.css",
  ],
  "/activity/details": [
    "/assets/css/ZTO/bootstrap.css",
    "/assets/css/ZTO/style.css",
    "/assets/css/ZTO/Home/all.min.css",
    "/assets/css/ZTO/style-home.css",
    "/assets/css/ZTO/Home/slicknav.min.css",
    "/assets/css/ZTO/Home/select2.min.css",
    "/assets/css/ZTO/custom.css",
    "/assets/css/ZTO/responsive.css",
    "/assets/css/ZTO/header.css",
    "/assets/css/ZTO/footer.css",
    "/assets/css/ZTO/theme.css",
    "/assets/css/ZTO/inline_style.css",
    "/assets/css/ZTO/components/flagicon.min.css",
    "/assets/css/ZTO/Romanian.css",
  ],
};
